public enum TokenType {
    // общие типы
    IDENTIFIER, OPERATOR, SEPARATOR,
    INTEGER_LITERAL, REAL_LITERAL, CHAR_LITERAL, STRING_LITERAL,
    PREPROCESSOR, EOF,

    // ключевые слова
    ABSTRACT, AS, BASE, BOOL, BREAK, BYTE, CASE, CATCH,
    CHAR_KEYWORD, CHECKED, CLASS, CONST, CONTINUE, DECIMAL,
    DEFAULT, DELEGATE, DO, DOUBLE, ELSE, ENUM, EVENT, EXPLICIT,
    EXTERN, FALSE, FINALLY, FIXED, FLOAT_KEYWORD, FOR, FOREACH,
    GOTO, IF, IMPLICIT, IN, INT, INTERFACE, INTERNAL, IS, LOCK,
    LONG, NAMESPACE, NEW, NULL, OBJECT, OPERATOR_KEYWORD, OUT,
    OVERRIDE, PARAMS, PRIVATE, PROTECTED, PUBLIC, READONLY, REF,
    RETURN, SBYTE, SEALED, SHORT, SIZEOF, STACKALLOC, STATIC,
    STRING, STRUCT, SWITCH, THIS, THROW, TRUE, TRY, TYPEOF,
    UINT, ULONG, UNCHECKED, UNSAFE, USHORT, USING, VIRTUAL, VOID,
    VOLATILE, WHILE
}